"""empty message

Revision ID: 19c2ffe6741e
Revises: d3e8f041463c
Create Date: 2023-06-10 19:33:38.597865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19c2ffe6741e'
down_revision = 'd3e8f041463c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('StartTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StartTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
