"""empty message

Revision ID: bde6eeba16fd
Revises: b0124389ec77
Create Date: 2023-06-12 20:27:26.653502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde6eeba16fd'
down_revision = 'b0124389ec77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
