"""empty message

Revision ID: d3e8f041463c
Revises: 25502a58360a
Create Date: 2023-06-10 17:47:16.913696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e8f041463c'
down_revision = '25502a58360a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
